# Generated by Django 3.2.6 on 2021-08-07 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-created']},
        ),
    ]
